# Generated by Django 4.1.7 on 2023-06-06 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hubble", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_of_holiday", models.DateField()),
                ("month_year", models.CharField(max_length=255)),
                ("reason", models.CharField(blank=True, max_length=255, null=True)),
                ("allow_check_in", models.BooleanField()),
            ],
            options={
                "db_table": "holidays",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=250)),
                ("start_date", models.DateField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_batches",
                        to="hubble.batch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_sub_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondary_mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_sub_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hubble.team"
                    ),
                ),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hubble.timeline",
                    ),
                ),
            ],
            options={
                "db_table": "sub_batches",
            },
        ),
        migrations.CreateModel(
            name="SubBatchTaskTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("days", models.FloatField()),
                (
                    "present_type",
                    models.CharField(
                        choices=[("Remote", "Remote"), ("In-Person", "In-Person")],
                        default="Remote",
                        max_length=255,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Task", "Task"),
                            ("Assessment", "Assessment"),
                            ("Cultural Meet", "Cultural Meet"),
                        ],
                        default="Task",
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("order", models.IntegerField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_timelines",
                        to="hubble.subbatch",
                    ),
                ),
            ],
            options={
                "db_table": "sub_batch_timeline_tasks",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InternDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("college", models.CharField(max_length=250)),
                ("expected_completion", models.DateField(null=True)),
                ("actual_completion", models.DateField(null=True)),
                ("comment", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_intern_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intern_sub_batch_details",
                        to="hubble.subbatch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intern_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intern_details",
            },
        ),
    ]
