# Generated by Django 4.1.3 on 2023-04-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinetask",
            name="days",
            field=models.FloatField(),
        ),
    ]
