# Generated by Django 4.1.7 on 2023-07-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0002_alter_assessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbatch',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_batches', to='hubble.timeline'),
        ),
    ]
