# Generated by Django 4.1.7 on 2023-07-14 12:20

from django.conf import settings
from django.db import migrations, models

def update_many_to_many(apps, schema_editor):

    sub_batch_model = apps.get_model("hubble", "SubBatch")
    user_model = apps.get_model("hubble", "User")

    with schema_editor.connection.cursor() as cursor:
        query = "SELECT id, secondary_mentor_id FROM sub_batches WHERE secondary_mentor_id IS NOT NULL"
        cursor.execute(query)
        values = cursor.fetchall()
        for value in values:
            user = user_model.objects.get(pk=value[1])
            sub_batch = sub_batch_model.objects.get(pk=value[0])
            sub_batch.secondary_mentors.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0003_extension_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subbatch",
            name="secondary_mentors",
            field=models.ManyToManyField(
                related_name="secondary_mentors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(update_many_to_many),
    ]
