# Generated by Django 4.1.7 on 2023-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0003_batch_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="extension",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
