# Generated by Django 4.1.7 on 2023-06-08 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0002_holiday_subbatch_subbatchtasktimeline_interndetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_extensions', to=settings.AUTH_USER_MODEL)),
                ('sub_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='hubble.subbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extensions',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('score', models.IntegerField()),
                ('is_retry', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hubble.extension')),
                ('sub_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubble.subbatch')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='hubble.subbatchtasktimeline')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
            },
        ),
    ]
