# Generated by Django 4.1.3 on 2023-04-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0002_alter_timelinetask_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeline",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hubble.users",
            ),
        ),
        migrations.AlterField(
            model_name="timeline",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
