# Generated by Django 4.1.7 on 2023-06-12 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0003_extension_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interndetail',
            name='sub_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_details', to='hubble.subbatch'),
        ),
        migrations.AlterField(
            model_name='timeline',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_active'),
        ),
    ]
