# Generated by Django 4.1.7 on 2023-07-14 12:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0003_subbatch_secondary_mentors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subbatch",
            name="secondary_mentor",
        ),
    ]
