# Generated by Django 4.1.7 on 2023-08-08 17:55

import core.db
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0003_batch_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraineeHoliday',
            fields=[
                ('created_at', core.db.DateTimeWithoutTZField(auto_now_add=True)),
                ('updated_at', core.db.DateTimeWithoutTZField(auto_now=True)),
                ('deleted_at', core.db.DateTimeWithoutTZField(null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_of_holiday', models.DateField()),
                ('month_year', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_check_in', models.BooleanField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hubble.batch')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trainee_holidays',
                'managed': True,
            },
        ),
    ]
