# Generated by Django 4.1.7 on 2023-06-13 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0004_alter_interndetail_sub_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interndetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intern_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
