# Generated by Django 4.1.7 on 2023-08-08 16:38

from django.utils import timezone
from django.db import migrations, models


def add_start_date_to_existing_batch(apps, schema_editor):
    Batch = apps.get_model("hubble", "Batch")
    for batch in Batch.objects.filter(deleted_at__isnull=True):
        oldest_start_date = (
            batch.sub_batches.order_by("start_date").values_list("start_date", flat=True).first()
        )
        if oldest_start_date:
            batch.start_date = oldest_start_date
            batch.save()
        else:
            batch.start_date = timezone.now().date()
            batch.save()


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0005_alter_subbatch_secondary_mentors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(add_start_date_to_existing_batch),
    ]
