# Generated by Django 4.1.7 on 2023-06-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubble', '0005_alter_interndetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbatchtasktimeline',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subbatchtasktimeline',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
