# Generated by Django 4.1.7 on 2023-08-23 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0005_alter_subbatch_secondary_mentors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="is_retry_needed",
            field=models.BooleanField(default=False, verbose_name="Is retry needed"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="present_status",
            field=models.BooleanField(default=True, verbose_name="Present status"),
        ),
        migrations.AddField(
            model_name="assessment",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_assessments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
