# Generated by Django 4.1.7 on 2023-09-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0007_alter_assessment_comment_alter_assessment_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="sub_batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="hubble.subbatch",
            ),
        ),
    ]
