# Generated by Django 4.1.7 on 2023-10-24 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hubble", "0007_traineeholiday"),
        ("hubble", "0008_alter_assessment_sub_batch"),
    ]

    operations = []
